Module Doing

    Public Sub CreateDoing()
        Call CreateUsualTable()
        Call CreateExcitingTable()
        Call CreateEatingTable("Breakfast")
        Call CreateEatingTable("Lunch")
        Call CreateEatingTable("Dinner")
        Call CreateSleepTable()
        Call CreateAsleepTable()
        Call CreateRestTable()
        Call CreateRegainTable()
        Call CreateRecoverTable()
    End Sub
    Private Sub CreateUsualTable()
        Dim tempTable As DataTable = New DataTable
        AddColumnToTable("System.UInt16", "Time", tempTable)
        AddColumnToTable("System.UInt16", "Force", tempTable)
        AddColumnToTable("System.Boolean", "Suprt", tempTable)
        AddColumnToTable("System.Boolean", "Effect", tempTable)
        AddRowToBreeding(0, 0, False, False, tempTable)
        AddRowToBreeding(10, 30, False, False, tempTable)
        AddRowToBreeding(20, 50, False, False, tempTable)
        AddRowToBreeding(30, 40, False, False, tempTable)
        AddRowToBreeding(40, 60, False, False, tempTable)
        AddRowToBreeding(50, 70, False, False, tempTable)
        AddRowToBreeding(60, 70, False, False, tempTable)
        AddRowToBreeding(70, 80, False, False, tempTable)
        AddRowToBreeding(80, 100, True, True, tempTable)
        AddRowToBreeding(90, 0, False, False, tempTable)
        tempTable.TableName = "Usual"
        FrmMain.DtsDoing.Tables.Add(tempTable)
        tempTable.Dispose()
    End Sub
    Private Sub CreateExcitingTable()
        Dim tempTable As DataTable = New DataTable
        AddColumnToTable("System.UInt16", "Time", tempTable)
        AddColumnToTable("System.UInt16", "Force", tempTable)
        AddColumnToTable("System.Boolean", "Suprt", tempTable)
        AddColumnToTable("System.Boolean", "Effect", tempTable)
        AddRowToBreeding(0, 0, False, False, tempTable)
        AddRowToBreeding(10, 30, False, False, tempTable)
        AddRowToBreeding(20, 70, False, False, tempTable)
        AddRowToBreeding(30, 60, False, False, tempTable)
        AddRowToBreeding(40, 80, False, False, tempTable)
        AddRowToBreeding(50, 80, True, False, tempTable)
        AddRowToBreeding(60, 100, False, False, tempTable)
        AddRowToBreeding(70, 90, False, False, tempTable)
        AddRowToBreeding(80, 120, False, False, tempTable)
        AddRowToBreeding(90, 120, False, False, tempTable)
        AddRowToBreeding(100, 170, False, False, tempTable)
        AddRowToBreeding(110, 180, False, False, tempTable)
        AddRowToBreeding(120, 210, True, False, tempTable)
        AddRowToBreeding(130, 200, False, False, tempTable)
        AddRowToBreeding(140, 240, False, False, tempTable)
        AddRowToBreeding(150, 240, False, False, tempTable)
        AddRowToBreeding(160, 270, False, False, tempTable)
        AddRowToBreeding(170, 320, True, True, tempTable)
        AddRowToBreeding(180, 0, False, False, tempTable)
        tempTable.TableName = "Exciting"
        FrmMain.DtsDoing.Tables.Add(tempTable)
        tempTable.Dispose()
    End Sub
    Private Sub CreateEatingTable(inpName As String)
        Dim tempTable As DataTable = New DataTable
        AddColumnToTable("System.UInt16", "Time", tempTable)
        AddColumnToTable("System.UInt16", "Force", tempTable)
        AddColumnToTable("System.Boolean", "Effect", tempTable)
        AddRowToEating(0, 0, False, tempTable)
        AddRowToEating(10, 20, False, tempTable)
        AddRowToEating(20, 20, False, tempTable)
        AddRowToEating(30, 30, False, tempTable)
        AddRowToEating(40, 40, False, tempTable)
        AddRowToEating(50, 30, True, tempTable)
        AddRowToEating(60, 0, False, tempTable)
        tempTable.TableName = inpName
        FrmMain.DtsDoing.Tables.Add(tempTable)
        tempTable.Dispose()
    End Sub
    Private Sub CreateSleepTable()
        Dim tempTable As DataTable = New DataTable
        AddColumnToTable("System.UInt16", "Time", tempTable)
        AddColumnToTable("System.UInt16", "Force", tempTable)
        AddColumnToTable("System.UInt16", "Dream", tempTable)
        AddColumnToTable("System.Boolean", "Effect", tempTable)
        AddRowToSleeping(0, 0, 0, False, tempTable)
        AddRowToSleeping(10, 20, 0, False, tempTable)
        AddRowToSleeping(20, 20, 0, False, tempTable)
        AddRowToSleeping(30, 20, 0, False, tempTable)
        AddRowToSleeping(40, 30, 0, False, tempTable)
        AddRowToSleeping(50, 50, 0, False, tempTable)
        AddRowToSleeping(60, 100, 100, False, tempTable)
        AddRowToSleeping(70, 100, 100, False, tempTable)
        AddRowToSleeping(80, 100, 100, False, tempTable)
        AddRowToSleeping(90, 100, 100, True, tempTable)
        AddRowToSleeping(100, 70, 0, False, tempTable)
        AddRowToSleeping(110, 60, 0, False, tempTable)
        AddRowToSleeping(120, 50, 0, False, tempTable)
        AddRowToSleeping(130, 80, 100, False, tempTable)
        AddRowToSleeping(140, 100, 100, False, tempTable)
        AddRowToSleeping(150, 100, 100, False, tempTable)
        AddRowToSleeping(160, 100, 100, True, tempTable)
        AddRowToSleeping(170, 70, 0, False, tempTable)
        AddRowToSleeping(180, 0, 0, False, tempTable)
        tempTable.TableName = "Sleep"
        FrmMain.DtsDoing.Tables.Add(tempTable)
        tempTable.Dispose()
    End Sub
    Private Sub CreateAsleepTable()
        Dim tempTable As DataTable = New DataTable
        AddColumnToTable("System.UInt16", "Time", tempTable)
        AddColumnToTable("System.UInt16", "Force", tempTable)
        AddColumnToTable("System.UInt16", "Dream", tempTable)
        AddColumnToTable("System.Boolean", "Effect", tempTable)
        AddRowToSleeping(0, 0, 0, False, tempTable)
        AddRowToSleeping(10, 10, 0, False, tempTable)
        AddRowToSleeping(20, 20, 0, False, tempTable)
        AddRowToSleeping(30, 40, 0, False, tempTable)
        AddRowToSleeping(40, 40, 0, False, tempTable)
        AddRowToSleeping(50, 50, 0, False, tempTable)
        AddRowToSleeping(60, 50, 0, False, tempTable)
        AddRowToSleeping(70, 60, 0, False, tempTable)
        AddRowToSleeping(80, 60, 0, False, tempTable)
        AddRowToSleeping(90, 70, 0, False, tempTable)
        AddRowToSleeping(100, 80, 100, False, tempTable)
        AddRowToSleeping(110, 80, 100, False, tempTable)
        AddRowToSleeping(120, 80, 100, True, tempTable)
        AddRowToSleeping(130, 70, 0, False, tempTable)
        AddRowToSleeping(140, 70, 0, False, tempTable)
        AddRowToSleeping(150, 60, 0, False, tempTable)
        AddRowToSleeping(160, 80, 0, False, tempTable)
        AddRowToSleeping(170, 100, 120, False, tempTable)
        AddRowToSleeping(180, 100, 120, False, tempTable)
        AddRowToSleeping(190, 100, 120, False, tempTable)
        AddRowToSleeping(200, 100, 120, True, tempTable)
        AddRowToSleeping(210, 90, 0, False, tempTable)
        AddRowToSleeping(220, 80, 0, False, tempTable)
        AddRowToSleeping(230, 80, 0, False, tempTable)
        AddRowToSleeping(240, 90, 0, False, tempTable)
        AddRowToSleeping(250, 90, 0, False, tempTable)
        AddRowToSleeping(260, 100, 0, False, tempTable)
        AddRowToSleeping(270, 120, 140, False, tempTable)
        AddRowToSleeping(280, 120, 140, False, tempTable)
        AddRowToSleeping(290, 120, 140, False, tempTable)
        AddRowToSleeping(300, 120, 140, False, tempTable)
        AddRowToSleeping(310, 120, 140, False, tempTable)
        AddRowToSleeping(320, 120, 140, True, tempTable)
        AddRowToSleeping(330, 110, 0, False, tempTable)
        AddRowToSleeping(340, 80, 0, False, tempTable)
        AddRowToSleeping(350, 90, 0, False, tempTable)
        AddRowToSleeping(360, 80, 0, False, tempTable)
        AddRowToSleeping(370, 80, 0, False, tempTable)
        AddRowToSleeping(380, 100, 0, False, tempTable)
        AddRowToSleeping(390, 110, 0, False, tempTable)
        AddRowToSleeping(400, 110, 0, False, tempTable)
        AddRowToSleeping(410, 110, 0, False, tempTable)
        AddRowToSleeping(420, 120, 0, False, tempTable)
        AddRowToSleeping(430, 120, 0, False, tempTable)
        AddRowToSleeping(440, 120, 0, False, tempTable)
        AddRowToSleeping(450, 140, 160, False, tempTable)
        AddRowToSleeping(460, 140, 160, False, tempTable)
        AddRowToSleeping(470, 140, 160, False, tempTable)
        AddRowToSleeping(480, 140, 160, False, tempTable)
        AddRowToSleeping(490, 140, 160, False, tempTable)
        AddRowToSleeping(500, 140, 160, True, tempTable)
        AddRowToSleeping(510, 130, 0, False, tempTable)
        AddRowToSleeping(520, 130, 0, False, tempTable)
        AddRowToSleeping(530, 100, 0, False, tempTable)
        AddRowToSleeping(540, 60, 0, False, tempTable)
        AddRowToSleeping(550, 70, 0, False, tempTable)
        AddRowToSleeping(560, 70, 0, False, tempTable)
        AddRowToSleeping(570, 80, 100, False, tempTable)
        AddRowToSleeping(580, 80, 100, False, tempTable)
        AddRowToSleeping(590, 80, 100, False, tempTable)
        AddRowToSleeping(600, 80, 100, True, tempTable)
        AddRowToSleeping(610, 60, 0, False, tempTable)
        AddRowToSleeping(620, 20, 0, False, tempTable)
        AddRowToSleeping(630, 0, 0, False, tempTable)
        tempTable.TableName = "Asleep"
        FrmMain.DtsDoing.Tables.Add(tempTable)
        tempTable.Dispose()
    End Sub
    Private Sub CreateRestTable()
        Dim tempTable As DataTable = New DataTable
        AddColumnToTable("System.UInt16", "Time", tempTable)
        AddColumnToTable("System.UInt16", "Force", tempTable)
        AddColumnToTable("System.Boolean", "Effect", tempTable)
        AddRowToResting(0, 0, False, tempTable)
        AddRowToResting(10, 10, False, tempTable)
        AddRowToResting(20, 10, False, tempTable)
        AddRowToResting(30, 20, False, tempTable)
        AddRowToResting(40, 30, False, tempTable)
        AddRowToResting(50, 30, False, tempTable)
        AddRowToResting(60, 30, False, tempTable)
        AddRowToResting(70, 40, False, tempTable)
        AddRowToResting(80, 40, False, tempTable)
        AddRowToResting(90, 40, False, tempTable)
        AddRowToResting(100, 40, False, tempTable)
        AddRowToResting(110, 20, False, tempTable)
        AddRowToResting(120, 0, False, tempTable)
        tempTable.TableName = "Rest"
        FrmMain.DtsDoing.Tables.Add(tempTable)
        tempTable.Dispose()
    End Sub
    Private Sub CreateRegainTable()
        Dim tempTable As DataTable = New DataTable
        AddColumnToTable("System.UInt16", "Time", tempTable)
        AddColumnToTable("System.UInt16", "Force", tempTable)
        AddColumnToTable("System.Boolean", "Effect", tempTable)
        AddRowToResting(0, 0, False, tempTable)
        AddRowToResting(10, 20, False, tempTable)
        AddRowToResting(20, 20, False, tempTable)
        AddRowToResting(30, 10, False, tempTable)
        AddRowToResting(40, 20, False, tempTable)
        AddRowToResting(50, 30, False, tempTable)
        AddRowToResting(60, 40, False, tempTable)
        AddRowToResting(70, 40, False, tempTable)
        AddRowToResting(80, 30, False, tempTable)
        AddRowToResting(90, 30, True, tempTable)
        AddRowToResting(100, 20, False, tempTable)
        AddRowToResting(110, 30, False, tempTable)
        AddRowToResting(120, 50, False, tempTable)
        AddRowToResting(130, 50, True, tempTable)
        AddRowToResting(140, 40, False, tempTable)
        AddRowToResting(150, 0, False, tempTable)
        tempTable.TableName = "Regain"
        FrmMain.DtsDoing.Tables.Add(tempTable)
        tempTable.Dispose()
    End Sub
    Private Sub CreateRecoverTable()
        Dim tempTable As DataTable = New DataTable
        AddColumnToTable("System.UInt16", "Time", tempTable)
        AddColumnToTable("System.UInt16", "Force", tempTable)
        AddColumnToTable("System.Boolean", "Effect", tempTable)
        AddRowToResting(0, 0, False, tempTable)
        AddRowToResting(10, 10, False, tempTable)
        AddRowToResting(20, 20, False, tempTable)
        AddRowToResting(30, 40, False, tempTable)
        AddRowToResting(40, 40, False, tempTable)
        AddRowToResting(50, 40, True, tempTable)
        AddRowToResting(60, 30, False, tempTable)
        AddRowToResting(70, 30, False, tempTable)
        AddRowToResting(80, 40, False, tempTable)
        AddRowToResting(90, 50, False, tempTable)
        AddRowToResting(100, 50, False, tempTable)
        AddRowToResting(110, 50, False, tempTable)
        AddRowToResting(120, 50, True, tempTable)
        AddRowToResting(130, 40, False, tempTable)
        AddRowToResting(140, 40, False, tempTable)
        AddRowToResting(150, 30, False, tempTable)
        AddRowToResting(160, 30, False, tempTable)
        AddRowToResting(170, 50, False, tempTable)
        AddRowToResting(180, 60, False, tempTable)
        AddRowToResting(190, 60, False, tempTable)
        AddRowToResting(200, 60, False, tempTable)
        AddRowToResting(210, 60, False, tempTable)
        AddRowToResting(220, 60, True, tempTable)
        AddRowToResting(230, 40, False, tempTable)
        AddRowToResting(240, 0, False, tempTable)
        tempTable.TableName = "Recover"
        FrmMain.DtsDoing.Tables.Add(tempTable)
        tempTable.Dispose()
    End Sub
    Private Sub AddRowToResting(inpT As Byte, inpF As UInt16, inpE As Boolean, ByRef oupTable As DataTable)
        Dim tempRow As DataRow = oupTable.NewRow()
        tempRow("Time") = inpT
        tempRow("Force") = inpF
        tempRow("Effect") = inpE
        oupTable.Rows.Add(tempRow)
    End Sub
    Private Sub AddRowToSleeping(inpT As UInt16, inpF As UInt16, inpD As Boolean, inpE As Boolean, ByRef oupTable As DataTable)
        Dim tempRow As DataRow = oupTable.NewRow()
        tempRow("Time") = inpT
        tempRow("Force") = inpF
        tempRow("Dream") = inpD
        tempRow("Effect") = inpE
        oupTable.Rows.Add(tempRow)
    End Sub
    Private Sub AddRowToEating(inpT As Byte, inpF As UInt16, inpE As Boolean, ByRef oupTable As DataTable)
        Dim tempRow As DataRow = oupTable.NewRow()
        tempRow("Time") = inpT
        tempRow("Force") = inpF
        tempRow("Effect") = inpE
        oupTable.Rows.Add(tempRow)
    End Sub
    Private Sub AddRowToBreeding(inpT As UInt16, inpF As UInt16, inpS As Boolean, inpE As Boolean, ByRef oupTable As DataTable)
        Dim tempRow As DataRow = oupTable.NewRow()
        tempRow("Time") = inpT
        tempRow("Force") = inpF
        tempRow("Suprt") = inpS
        tempRow("Effect") = inpE
        oupTable.Rows.Add(tempRow)
    End Sub
End Module
