Module Doing

    Public Sub CreateDoing()
        Call CreateUsualTable()
        Call CreateExcitingTable()
        Call CreateEatingTable("Breakfast")
        Call CreateEatingTable("Lunch")
        Call CreateEatingTable("Dinner")
        Call CreateSleepTable()
        Call CreateAsleepTable()
        Call CreateRestTable()
        Call CreateRegainTable()
        Call CreateRecoverTable()
    End Sub
    Private Sub CreateUsualTable()
        Dim tempTable As DataTable = New DataTable
        Call CreateDoingTableSchema("Usual", tempTable)
        AddRowToDoing(0, 0, False, False, tempTable)
        AddRowToDoing(10, 30, False, False, tempTable)
        AddRowToDoing(20, 50, False, False, tempTable)
        AddRowToDoing(30, 40, False, False, tempTable)
        AddRowToDoing(40, 60, False, False, tempTable)
        AddRowToDoing(50, 70, False, False, tempTable)
        AddRowToDoing(60, 70, False, False, tempTable)
        AddRowToDoing(70, 80, False, False, tempTable)
        AddRowToDoing(80, 100, True, True, tempTable)
        AddRowToDoing(90, 0, False, False, tempTable)
        FrmMain.DtsDoing.Tables.Add(tempTable)
        tempTable.Dispose()
    End Sub
    Private Sub CreateExcitingTable()
        Dim tempTable As DataTable = New DataTable
        Call CreateDoingTableSchema("Exciting", tempTable)
        AddRowToDoing(0, 0, False, False, tempTable)
        AddRowToDoing(10, 30, False, False, tempTable)
        AddRowToDoing(20, 70, False, False, tempTable)
        AddRowToDoing(30, 60, False, False, tempTable)
        AddRowToDoing(40, 80, False, False, tempTable)
        AddRowToDoing(50, 80, True, False, tempTable)
        AddRowToDoing(60, 100, False, False, tempTable)
        AddRowToDoing(70, 90, False, False, tempTable)
        AddRowToDoing(80, 120, False, False, tempTable)
        AddRowToDoing(90, 120, False, False, tempTable)
        AddRowToDoing(100, 170, False, False, tempTable)
        AddRowToDoing(110, 180, False, False, tempTable)
        AddRowToDoing(120, 210, True, False, tempTable)
        AddRowToDoing(130, 200, False, False, tempTable)
        AddRowToDoing(140, 240, False, False, tempTable)
        AddRowToDoing(150, 240, False, False, tempTable)
        AddRowToDoing(160, 270, False, False, tempTable)
        AddRowToDoing(170, 320, True, True, tempTable)
        AddRowToDoing(180, 0, False, False, tempTable)
        FrmMain.DtsDoing.Tables.Add(tempTable)
        tempTable.Dispose()
    End Sub
    Private Sub CreateEatingTable(inpName As String)
        Dim tempTable As DataTable = New DataTable
        CreateDoingTableSchema(inpName, tempTable)
        AddRowToDoing(0, 0, False, False, tempTable)
        AddRowToDoing(10, 20, False, False, tempTable)
        AddRowToDoing(20, 20, False, False, tempTable)
        AddRowToDoing(30, 30, False, False, tempTable)
        AddRowToDoing(40, 40, False, False, tempTable)
        AddRowToDoing(50, 30, False, True, tempTable)
        AddRowToDoing(60, 0, False, False, tempTable)
        FrmMain.DtsDoing.Tables.Add(tempTable)
        tempTable.Dispose()
    End Sub
    Private Sub CreateSleepTable()
        Dim tempTable As DataTable = New DataTable
        Call CreateDoingTableSchema("Sleep", tempTable)
        AddRowToDoing(0, 0, False, False, tempTable)
        AddRowToDoing(10, 20, False, False, tempTable)
        AddRowToDoing(20, 20, False, False, tempTable)
        AddRowToDoing(30, 20, False, False, tempTable)
        AddRowToDoing(40, 30, False, False, tempTable)
        AddRowToDoing(50, 50, False, False, tempTable)
        AddRowToDoing(60, 70, True, False, tempTable)
        AddRowToDoing(70, 80, True, False, tempTable)
        AddRowToDoing(80, 80, True, False, tempTable)
        AddRowToDoing(90, 80, True, True, tempTable)
        AddRowToDoing(100, 70, False, False, tempTable)
        AddRowToDoing(110, 60, False, False, tempTable)
        AddRowToDoing(120, 50, False, False, tempTable)
        AddRowToDoing(130, 80, True, False, tempTable)
        AddRowToDoing(140, 100, True, False, tempTable)
        AddRowToDoing(150, 100, True, False, tempTable)
        AddRowToDoing(160, 100, True, True, tempTable)
        AddRowToDoing(170, 80, False, False, tempTable)
        AddRowToDoing(180, 70, False, False, tempTable)
        AddRowToDoing(190, 80, False, False, tempTable)
        AddRowToDoing(200, 80, False, False, tempTable)
        AddRowToDoing(210, 90, False, False, tempTable)
        AddRowToDoing(220, 100, False, False, tempTable)
        AddRowToDoing(230, 110, True, False, tempTable)
        AddRowToDoing(240, 110, True, False, tempTable)
        AddRowToDoing(250, 110, True, False, tempTable)
        AddRowToDoing(260, 110, True, True, tempTable)
        AddRowToDoing(270, 100, False, False, tempTable)
        AddRowToDoing(280, 80, False, False, tempTable)
        AddRowToDoing(290, 70, False, False, tempTable)
        AddRowToDoing(300, 80, False, False, tempTable)
        AddRowToDoing(310, 70, False, False, tempTable)
        AddRowToDoing(320, 80, False, False, tempTable)
        AddRowToDoing(330, 90, True, False, tempTable)
        AddRowToDoing(340, 90, True, True, tempTable)
        AddRowToDoing(350, 70, False, False, tempTable)
        AddRowToDoing(360, 0, False, False, tempTable)
        FrmMain.DtsDoing.Tables.Add(tempTable)
        tempTable.Dispose()
    End Sub
    Private Sub CreateAsleepTable()
        Dim tempTable As DataTable = New DataTable
        Call CreateDoingTableSchema("Asleep", tempTable)
        AddRowToDoing(0, 0, False, False, tempTable)
        AddRowToDoing(10, 10, False, False, tempTable)
        AddRowToDoing(20, 20, False, False, tempTable)
        AddRowToDoing(30, 40, False, False, tempTable)
        AddRowToDoing(40, 40, False, False, tempTable)
        AddRowToDoing(50, 50, False, False, tempTable)
        AddRowToDoing(60, 50, False, False, tempTable)
        AddRowToDoing(70, 60, False, False, tempTable)
        AddRowToDoing(80, 60, False, False, tempTable)
        AddRowToDoing(90, 70, False, False, tempTable)
        AddRowToDoing(100, 80, True, False, tempTable)
        AddRowToDoing(110, 80, True, False, tempTable)
        AddRowToDoing(120, 80, True, True, tempTable)
        AddRowToDoing(130, 70, False, False, tempTable)
        AddRowToDoing(140, 70, False, False, tempTable)
        AddRowToDoing(150, 60, False, False, tempTable)
        AddRowToDoing(160, 80, False, False, tempTable)
        AddRowToDoing(170, 100, True, False, tempTable)
        AddRowToDoing(180, 100, True, False, tempTable)
        AddRowToDoing(190, 100, True, False, tempTable)
        AddRowToDoing(200, 100, True, True, tempTable)
        AddRowToDoing(210, 90, False, False, tempTable)
        AddRowToDoing(220, 80, False, False, tempTable)
        AddRowToDoing(230, 80, False, False, tempTable)
        AddRowToDoing(240, 90, False, False, tempTable)
        AddRowToDoing(250, 90, False, False, tempTable)
        AddRowToDoing(260, 100, False, False, tempTable)
        AddRowToDoing(270, 120, True, False, tempTable)
        AddRowToDoing(280, 120, True, False, tempTable)
        AddRowToDoing(290, 120, True, False, tempTable)
        AddRowToDoing(300, 120, True, False, tempTable)
        AddRowToDoing(310, 120, True, False, tempTable)
        AddRowToDoing(320, 120, True, True, tempTable)
        AddRowToDoing(330, 110, False, False, tempTable)
        AddRowToDoing(340, 80, False, False, tempTable)
        AddRowToDoing(350, 90, False, False, tempTable)
        AddRowToDoing(360, 80, False, False, tempTable)
        AddRowToDoing(370, 80, False, False, tempTable)
        AddRowToDoing(380, 100, False, False, tempTable)
        AddRowToDoing(390, 110, False, False, tempTable)
        AddRowToDoing(400, 110, False, False, tempTable)
        AddRowToDoing(410, 110, False, False, tempTable)
        AddRowToDoing(420, 120, False, False, tempTable)
        AddRowToDoing(430, 120, False, False, tempTable)
        AddRowToDoing(440, 120, False, False, tempTable)
        AddRowToDoing(450, 140, True, False, tempTable)
        AddRowToDoing(460, 140, True, False, tempTable)
        AddRowToDoing(470, 140, True, False, tempTable)
        AddRowToDoing(480, 140, True, False, tempTable)
        AddRowToDoing(490, 140, True, False, tempTable)
        AddRowToDoing(500, 140, True, True, tempTable)
        AddRowToDoing(510, 130, False, False, tempTable)
        AddRowToDoing(520, 130, False, False, tempTable)
        AddRowToDoing(530, 100, False, False, tempTable)
        AddRowToDoing(540, 60, False, False, tempTable)
        AddRowToDoing(550, 70, False, False, tempTable)
        AddRowToDoing(560, 70, False, False, tempTable)
        AddRowToDoing(570, 80, True, False, tempTable)
        AddRowToDoing(580, 80, True, False, tempTable)
        AddRowToDoing(590, 80, True, False, tempTable)
        AddRowToDoing(600, 80, True, True, tempTable)
        AddRowToDoing(610, 60, False, False, tempTable)
        AddRowToDoing(620, 20, False, False, tempTable)
        AddRowToDoing(630, 0, False, False, tempTable)
        FrmMain.DtsDoing.Tables.Add(tempTable)
        tempTable.Dispose()
    End Sub
    Private Sub CreateRestTable()
        Dim tempTable As DataTable = New DataTable
        Call CreateDoingTableSchema("Rest", tempTable)
        AddRowToDoing(0, 0, False, False, tempTable)
        AddRowToDoing(10, 10, False, False, tempTable)
        AddRowToDoing(20, 10, False, False, tempTable)
        AddRowToDoing(30, 20, False, False, tempTable)
        AddRowToDoing(40, 30, False, False, tempTable)
        AddRowToDoing(50, 30, False, False, tempTable)
        AddRowToDoing(60, 30, False, True, tempTable)
        AddRowToDoing(70, 40, False, False, tempTable)
        AddRowToDoing(80, 40, False, False, tempTable)
        AddRowToDoing(90, 40, False, False, tempTable)
        AddRowToDoing(100, 40, False, True, tempTable)
        AddRowToDoing(110, 20, False, False, tempTable)
        AddRowToDoing(120, 0, False, False, tempTable)
        FrmMain.DtsDoing.Tables.Add(tempTable)
        tempTable.Dispose()
    End Sub
    Private Sub CreateRegainTable()
        Dim tempTable As DataTable = New DataTable
        Call CreateDoingTableSchema("Regain", tempTable)
        AddRowToDoing(0, 0, False, False, tempTable)
        AddRowToDoing(10, 20, False, False, tempTable)
        AddRowToDoing(20, 20, False, False, tempTable)
        AddRowToDoing(30, 10, False, False, tempTable)
        AddRowToDoing(40, 20, False, False, tempTable)
        AddRowToDoing(50, 30, False, False, tempTable)
        AddRowToDoing(60, 40, False, False, tempTable)
        AddRowToDoing(70, 40, False, False, tempTable)
        AddRowToDoing(80, 30, False, False, tempTable)
        AddRowToDoing(90, 30, False, True, tempTable)
        AddRowToDoing(100, 20, False, False, tempTable)
        AddRowToDoing(110, 30, False, False, tempTable)
        AddRowToDoing(120, 50, False, False, tempTable)
        AddRowToDoing(130, 50, False, True, tempTable)
        AddRowToDoing(140, 40, False, False, tempTable)
        AddRowToDoing(150, 0, False, False, tempTable)
        FrmMain.DtsDoing.Tables.Add(tempTable)
        tempTable.Dispose()
    End Sub
    Private Sub CreateRecoverTable()
        Dim tempTable As DataTable = New DataTable
        Call CreateDoingTableSchema("Recover", tempTable)
        AddRowToDoing(0, 0, False, False, tempTable)
        AddRowToDoing(10, 10, False, False, tempTable)
        AddRowToDoing(20, 20, False, False, tempTable)
        AddRowToDoing(30, 40, False, False, tempTable)
        AddRowToDoing(40, 40, False, False, tempTable)
        AddRowToDoing(50, 40, False, True, tempTable)
        AddRowToDoing(60, 30, False, False, tempTable)
        AddRowToDoing(70, 30, False, False, tempTable)
        AddRowToDoing(80, 40, False, False, tempTable)
        AddRowToDoing(90, 50, False, False, tempTable)
        AddRowToDoing(100, 50, False, False, tempTable)
        AddRowToDoing(110, 50, False, False, tempTable)
        AddRowToDoing(120, 50, False, True, tempTable)
        AddRowToDoing(130, 40, False, False, tempTable)
        AddRowToDoing(140, 40, False, False, tempTable)
        AddRowToDoing(150, 30, False, False, tempTable)
        AddRowToDoing(160, 30, False, False, tempTable)
        AddRowToDoing(170, 50, False, False, tempTable)
        AddRowToDoing(180, 60, False, False, tempTable)
        AddRowToDoing(190, 60, False, False, tempTable)
        AddRowToDoing(200, 60, False, False, tempTable)
        AddRowToDoing(210, 60, False, False, tempTable)
        AddRowToDoing(220, 60, False, True, tempTable)
        AddRowToDoing(230, 40, False, False, tempTable)
        AddRowToDoing(240, 0, False, False, tempTable)
        FrmMain.DtsDoing.Tables.Add(tempTable)
        tempTable.Dispose()
    End Sub

    Private Sub CreateDoingTableSchema(inpTN As String, ByRef oupTable As DataTable)
        AddColumnToTable("System.UInt16", "Time", oupTable)
        AddColumnToTable("System.UInt16", "Force", oupTable)
        AddColumnToTable("System.Boolean", "Utility", oupTable)
        AddColumnToTable("System.Boolean", "Effect", oupTable)
        oupTable.TableName = inpTN
    End Sub
    Private Sub AddRowToDoing(inpT As UInt16, inpF As UInt16, inpU As Boolean, inpE As Boolean, ByRef oupTable As DataTable)
        Dim tempRow As DataRow = oupTable.NewRow()
        tempRow("Time") = inpT
        tempRow("Force") = inpF
        tempRow("Utility") = inpU
        tempRow("Effect") = inpE
        oupTable.Rows.Add(tempRow)
    End Sub
End Module
